# Generated by Django 5.0.7 on 2024-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_weatherdata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedSolarEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('predicted_energy', models.FloatField()),
            ],
        ),
    ]
